import os
from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent
from langchain_core.messages.ai import AIMessage
from dotenv import load_dotenv

# Load environment variables from .env (if available)
load_dotenv()

# Fetch API keys from environment variables
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY not found in environment variables.")
if not TAVILY_API_KEY:
    raise ValueError("TAVILY_API_KEY not found in environment variables.")

# Optionally, create a search tool instance to be reused (if needed)
search_tool = TavilySearchResults(max_results=2)

# Define default system prompt (can be overridden by the request)
DEFAULT_SYSTEM_PROMPT = "Act as an AI chatbot who is smart and friendly"

def get_response_from_ai_agent(llm_id, query, allow_search, system_prompt):
    """
    Creates an AI agent using the Groq LLM (with optional web search)
    and returns the agent's response for the given query.
    
    Parameters:
      - llm_id (str): The model identifier to use.
      - query (list): List of query messages.
      - allow_search (bool): Whether to allow the web search tool.
      - system_prompt (str): The system prompt for the agent.
    
    Returns:
      - str: The final response from the AI agent.
    """
    # Initialize Groq LLM with the provided model and API key
    llm = ChatGroq(model=llm_id, api_key=GROQ_API_KEY)
    
    # Use search tool if web search is allowed
    tools = [TavilySearchResults(max_results=2)] if allow_search else []
    
    # Create the agent with the specified model, tools, and system prompt
    agent = create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=system_prompt
    )
    
    # Prepare the state with the provided query (list of messages)
    state = {"messages": query}
    
    # Invoke the agent to get a response
    response = agent.invoke(state)
    messages = response.get("messages", [])
    
    # Extract AI message contents and return the last one
    ai_messages = [message.content for message in messages if isinstance(message, AIMessage)]
    return ai_messages[-1] if ai_messages else "No response generated by the agent."